# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdown',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
